# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-12 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=64)),
                ('annotation', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('power', models.ManyToManyField(to='rbac.Power')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('role', models.ManyToManyField(to='rbac.Role')),
            ],
        ),
    ]
