# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-13 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together=set([('username', 'password')]),
        ),
    ]
